### ISSUE TITLE
Success with Stamped Messages?   

### ISSUE THREAD

**Issue by wegunterjr** [SynapseProgramming/ros2labview_examples#4]
have you tried a stamped message?
We are trying to just do an ackermannDrive Stamped, but not getting the header to work just right:
The header message is being filled on the labview side, but only the drive messages are able to be updated.
Thoughts?
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
drive:
  steering_angle: 1.401298464324817e-45
  steering_angle_velocity: 0.0
  speed: 0.0
  acceleration: 0.0
  jerk: 0.0
```
